### ISSUE TITLE
`netcdf4` segfault issue

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#148]
**Updated description**
This issue was noticed on CI where the netcdf4 library used to be installed through `pip`. Similar to what was noticed in https://github.com/oceanmodeling/adcircpy/issues/188 we need to install `netcdf4` by rebuilding it (the binaries from pypi seem to have some issues with library binaries). Note that this requires CI to install `libnetcdf` and `libhdf5` and then:
```bsah
python -m pip install --upgrade --force-reinstall --no-deps --no-cache-dir netcdf4 --no-binary netcdf4
```

**Comment by SorooshMani-NOAA** [comment]
If I install `ensembleperturbation` locally using only `pip` I get the same crash issue. This seems to be an issue related to netcdf/hdf5 library:

```gdb
Thread 69 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6626c640 (LWP 5089)]
0x00007fff554d336e in H5SL_search () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libhdf5-7b49ac63.so.310.2.0
#0  0x00007fff554d336e in H5SL_search () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libhdf5-7b49ac63.so.310.2.0
#1  0x00007fff5548657f in H5P_set () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libhdf5-7b49ac63.so.310.2.0
#2  0x00007fff5531d6cc in H5CX_pop () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libhdf5-7b49ac63.so.310.2.0
#3  0x00007fff553203a9 in H5Dget_space ()                                                                                                                                 from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libhdf5-7b49ac63.so.310.2.0                                       #4  0x00007fff557962de in nc4_find_dim_len ()
   from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libnetcdf-6ebc343d.so.19                                          #5  0x00007fff557956d8 in HDF5_inq_dim () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libnetcdf-6ebc343d.so.19
#6  0x00007fff5575fb5a in nc_inq_dimlen () from /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libnetcdf-6ebc343d.so.19
#7  0x00007fff55a6a258 in __pyx_pf_7netCDF4_8_netCDF4_9Dimension_8__len__ (__pyx_v_self=0x7fff55b3efc0) at src/netCDF4/_netCDF4.c:46964
#8  __pyx_pw_7netCDF4_8_netCDF4_9Dimension_9__len__ (__pyx_v_self=<netCDF4._netCDF4.Dimension at remote 0x7fff55b3efc0>) at src/netCDF4/_netCDF4.c:46919
#9  0x00007fff55a6bfff in __pyx_pf_7netCDF4_8_netCDF4_8Variable_5shape___get__ (__pyx_v_self=0x7fff55b368e0) at src/netCDF4/_netCDF4.c:57974
#10 __pyx_pw_7netCDF4_8_netCDF4_8Variable_5shape_1__get__ (__pyx_v_self=<netCDF4._netCDF4.Variable at remote 0x7fff55b368e0>) at src/netCDF4/_netCDF4.c:57810
#11 __pyx_getprop_7netCDF4_8_netCDF4_8Variable_shape (o=<netCDF4._netCDF4.Variable at remote 0x7fff55b368e0>, x=<optimized out>) at src/netCDF4/_netCDF4.c:108391
#12 0x0000555555696c82 in _PyObject_GenericGetAttrWithDict (obj=<optimized out>, name=<optimized out>, dict=<optimized out>, suppress=<optimized out>)
   at /usr/local/src/conda/python-3.10.14/Objects/object.c:1254
#13 0x00007fff55a37470 in __pyx_tp_getattro_7netCDF4_8_netCDF4_Variable (o=<netCDF4._netCDF4.Variable at remote 0x7fff55b368e0>, n='shape')
   at src/netCDF4/_netCDF4.c:108355
#14 0x00007fff55a10eac in __Pyx_PyObject_GetAttrStr (attr_name=<optimized out>, obj=<netCDF4._netCDF4.Variable at remote 0x7fff55b368e0>)
   at src/netCDF4/_netCDF4.c:120721
#15 __pyx_pf_7netCDF4_8_netCDF4_8Variable_48__getitem__ (__pyx_v_self=0x7fff55b368e0,                                                                                      __pyx_v_elem=(<slice at remote 0x7fff54bea700>, <slice at remote 0x7fff54beacc0>)) at src/netCDF4/_netCDF4.c:64177
#16 0x0000555555698bf3 in cfunction_vectorcall_FASTCALL (func=<built-in method getitem of module object at remote 0x7ffff7b0ee30>, args=0x7fff54b89b10,
    nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.14/Objects/methodobject.c:430
#17 0x0000555555688850 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7fff54b89b10,                                                            callable=<built-in method getitem of module object at remote 0x7ffff7b0ee30>, tstate=0x5555592fcd70)
   at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:114
#18 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fff54b89b10, callable=<built-in method getitem of module object at remote 0x7ffff7b0ee30>)
    at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:123                                                                                              #19 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fff66269790, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.14/Python/ceval.c:5893
#20 _PyEval_EvalFrameDefault (tstate=<optimized out>,
    f=Frame 0x7fff54b89970, for file /home/smani/miniconda3/envs/netcdfcrash/lib/python3.10/site-packages/xarray/backends/netCDF4_.py, line 113, in _getitem (self=<NetCDF4ArrayWrapper at remote 0x7fff55b66e00>, key=(<slice at remote 0x7fff54bea700>, <slice at remote 0x7fff54beacc0>), getitem=<built-in method getitem of module object at remote 0x7ffff7b0ee30>, original_array=<netCDF4._netCDF4.Variable at remote 0x7fff55b368e0>), throwflag=<optimized out>)                                               at /usr/local/src/conda/python-3.10.14/Python/ceval.c:4213                            
```
